const TOPICS = [
  {
    topic: "Coffee & Café",
    sentences: [
      { en: "Could I get a medium latte to go?", ko: "라떼 톨 사이즈 테이크아웃으로 부탁해요." },
      { en: "Do you have any non-dairy options today?", ko: "오늘 비유제품 옵션이 있나요?" },
      { en: "I usually order a cappuccino in the morning.", ko: "아침에는 보통 카푸치노를 주문해요." },
      { en: "She asked if the cold brew was strong.", ko: "그녀는 콜드브루가 진한지 물었어요." },
      { en: "Had I known it was bitter, I wouldn’t have ordered it.", ko: "쓴 줄 알았다면 주문하지 않았을 거예요." },
      { en: "Can you make it half sweet, please?", ko: "절반만 달게 해줄 수 있나요?" },
      { en: "They offered me a free refill yesterday.", ko: "어제 무료 리필을 해줬어요." },
      { en: "By the time I arrived, the café had already closed.", ko: "내가 도착했을 때는 카페가 이미 문을 닫았었어요." },
      { en: "Do you take Apple Pay here?", ko: "여기서 애플페이 결제 되나요?" },
      { en: "I’ll have whatever your seasonal special is.", ko: "오늘의 시즌 메뉴로 주세요." },
      { en: "Would you mind warming this up a bit more?", ko: "조금 더 데워주시겠어요?" },
      { en: "If I had studied here, I would have focused better.", ko: "여기서 공부했더라면 집중이 더 잘 됐을 텐데." },
      { en: "She has never tried oat milk in her coffee.", ko: "그녀는 커피에 오트밀크를 넣어본 적이 없어요." },
      { en: "What pastry do you recommend today?", ko: "오늘은 어떤 페이스트리를 추천하시나요?" },
      { en: "The café used to be quieter in the evenings.", ko: "이 카페는 예전에는 저녁에 더 조용했어요." },
      { en: "I might order a decaf espresso later.", ko: "나중에 디카페인 에스프레소를 주문할 수도 있어요." },
      { en: "He asked me whether tipping was included.", ko: "그는 팁이 포함되어 있는지 물었어요." },
      { en: "By now, I’ve already had two cups of coffee.", ko: "지금까지 벌써 커피 두 잔을 마셨어요." },
      { en: "Do you offer any loyalty rewards?", ko: "멤버십 포인트 적립이 있나요?" },
      { en: "I wish this café stayed open all night.", ko: "이 카페가 밤새 열려 있으면 좋겠어요." },
      { en: "Is there Wi-Fi, and what’s the password?", ko: "와이파이가 있나요? 비밀번호는 무엇인가요?" }
    ]
  },
  {
    topic: "Morning Routine",
    sentences: [
      { en: "I woke up early to stretch.", ko: "일찍 일어나 스트레칭을 했어요." },
      { en: "Did you eat breakfast today?", ko: "오늘 아침 식사했나요?" },
      { en: "I usually check my phone right after waking up.", ko: "일어나자마자 보통 휴대폰을 확인해요." },
      { en: "She had already finished her workout before 7 a.m.", ko: "그녀는 오전 7시 전에 운동을 이미 끝냈어요." },
      { en: "If I had gone jogging, I would feel more refreshed.", ko: "조깅을 했더라면 더 상쾌했을 텐데." },
      { en: "I brushed my teeth quickly.", ko: "빨리 양치했어요." },
      { en: "Have you ever meditated in the morning?", ko: "아침에 명상해 본 적 있나요?" },
      { en: "I always pack my bag before leaving home.", ko: "집을 나서기 전에 항상 가방을 챙겨요." },
      { en: "He asked if I had ironed my shirt.", ko: "그는 내가 셔츠를 다렸는지 물었어요." },
      { en: "By the time she woke up, I had already left.", ko: "그녀가 일어났을 때 나는 이미 떠났었어요." },
      { en: "I make a to-do list for the day.", ko: "오늘 할 일 목록을 작성해요." },
      { en: "Did you remember to water the plants this morning?", ko: "오늘 아침에 화분에 물 주는 거 기억했나요?" },
      { en: "I try not to skip breakfast.", ko: "아침 식사를 거르지 않으려고 노력해요." },
      { en: "He had already showered before breakfast.", ko: "그는 아침을 먹기 전에 이미 샤워했어요." },
      { en: "I sometimes snooze the alarm too many times.", ko: "알람을 너무 여러 번 미룰 때가 있어요." },
      { en: "I’d rather drink water than coffee first thing.", ko: "아침에 제일 먼저 커피보다 물을 마시는 게 좋아요." },
      { en: "She asked me whether I had made my bed.", ko: "그녀는 내가 침대를 정리했는지 물었어요." },
      { en: "I have practiced yoga every morning this week.", ko: "이번 주에는 매일 아침 요가를 했어요." },
      { en: "If I wake up late, I’ll skip stretching.", ko: "늦게 일어나면 스트레칭을 건너뛰어요." },
      { en: "He said he always reads the news while eating.", ko: "그는 식사하면서 항상 뉴스를 본다고 했어요." },
      { en: "By now, I’ve already finished my morning routine.", ko: "지금쯤이면 아침 루틴을 이미 끝냈어요." }
    ]
  },
  {
    topic: "Commuting",
    sentences: [
      { en: "How long does your commute take?", ko: "출퇴근에 얼마나 걸리나요?" },
      { en: "I usually take the subway.", ko: "나는 보통 지하철을 타요." },
      { en: "Yesterday the bus was delayed.", ko: "어제 버스가 지연됐어요." },
      { en: "Had I left earlier, I wouldn’t have been late.", ko: "좀 더 일찍 나갔다면 늦지 않았을 거예요." },
      { en: "I read books during my commute.", ko: "출퇴근 시간에 책을 읽어요." },
      { en: "Do you cycle to work sometimes?", ko: "가끔 자전거로 출근하나요?" },
      { en: "She had already arrived before I did.", ko: "그녀는 내가 도착하기 전에 이미 도착했어요." },
      { en: "I might try carpooling next week.", ko: "다음 주에는 카풀을 시도할지도 몰라요." },
      { en: "He asked if I had missed the train.", ko: "그는 내가 기차를 놓쳤는지 물었어요." },
      { en: "By the time I got to the station, the train had left.", ko: "내가 역에 도착했을 때 기차는 이미 떠났었어요." },
      { en: "Commuting feels longer on rainy days.", ko: "비 오는 날에는 출퇴근이 더 길게 느껴져요." },
      { en: "If I lived closer, I would walk to work.", ko: "더 가까이 산다면 걸어서 출근할 텐데." },
      { en: "Have you ever worked remotely instead of commuting?", ko: "출근 대신 원격 근무를 해본 적 있나요?" },
      { en: "I often listen to podcasts on the train.", ko: "기차에서 팟캐스트를 자주 들어요." },
      { en: "The subway used to be less crowded before 8.", ko: "지하철은 8시 이전에는 덜 붐볐어요." },
      { en: "She asked me whether I had taken a taxi.", ko: "그녀는 내가 택시를 탔는지 물었어요." },
      { en: "I had been standing the whole ride.", ko: "나는 내내 서 있었어요." },
      { en: "If the bus comes late, I’ll be late too.", ko: "버스가 늦게 오면 나도 늦을 거예요." },
      { en: "By now, I have already adapted to the commute.", ko: "지금쯤이면 출퇴근에 이미 적응했어요." },
      { en: "I wish commuting were shorter.", ko: "출퇴근이 더 짧았으면 좋겠어요." },
      { en: "She takes the train every day without fail.", ko: "그녀는 매일 빠짐없이 기차를 타요." }
    ]
  },
  {
    topic: "Emails",
    sentences: [
      { en: "I sent out three emails this morning.", ko: "오늘 아침에 이메일 세 통을 보냈어요." },
      { en: "Did you reply to the manager’s email?", ko: "매니저 이메일에 답장했나요?" },
      { en: "I usually check emails before starting work.", ko: "업무 시작 전에 보통 이메일을 확인해요." },
      { en: "She had already answered before I wrote mine.", ko: "내가 쓰기도 전에 그녀는 이미 답장을 했어요." },
      { en: "If I had proofread, the email would have been clearer.", ko: "교정을 했더라면 이메일이 더 명확했을 거예요." },
      { en: "I flagged the urgent message.", ko: "긴급 메일에 플래그를 표시했어요." },
      { en: "By the time I checked, the email had been deleted.", ko: "내가 확인했을 때 메일이 삭제됐었어요." },
      { en: "He asked me if I had attached the file.", ko: "그는 내가 파일을 첨부했는지 물었어요." },
      { en: "I have written five drafts today.", ko: "오늘 다섯 개의 초안을 작성했어요." },
      { en: "Do you organize your inbox regularly?", ko: "받은 편지함을 정기적으로 정리하나요?" },
      { en: "The email system used to be slower.", ko: "이메일 시스템은 예전에는 더 느렸어요." },
      { en: "I might set an auto-reply next week.", ko: "다음 주에 자동 회신을 설정할지도 몰라요." },
      { en: "She asked whether I had missed her email.", ko: "그녀는 내가 이메일을 놓쳤는지 물었어요." },
      { en: "I had replied by the time the meeting started.", ko: "회의가 시작될 때까지 나는 답장을 했어요." },
      { en: "If I don’t check emails, I’ll miss updates.", ko: "이메일을 확인하지 않으면 업데이트를 놓칠 거예요." },
      { en: "Have you ever written a formal complaint email?", ko: "공식적인 불만 이메일을 써본 적 있나요?" },
      { en: "I deleted several spam messages today.", ko: "오늘 스팸 메일 몇 개를 삭제했어요." },
      { en: "She always double-checks attachments.", ko: "그녀는 항상 첨부 파일을 두 번 확인해요." },
      { en: "I wish email writing were faster.", ko: "이메일 작성이 더 빨랐으면 좋겠어요." },
      { en: "By now, I have already cleared my inbox.", ko: "지금쯤이면 받은 편지함을 이미 정리했어요." },
      { en: "He receives over 50 emails daily.", ko: "그는 매일 50통 넘는 이메일을 받아요." }
    ]
  },

      window.TOPICS = TOPICS;
