Array.isArray(TOPICS) && TOPICS.length   // → (예: 10, 20, 100 ...)
Array.isArray(TITLES) && TITLES.length   // → TOPICS 개수와 동일해야 정상
typeof bank21                            // → "function"
TOPIC_BANKS[TITLES[0]].length            // → 21 이어야 정상
// Fully handcrafted topics.js — 100 topics × 21 sentences each
// topics.js (1~10번 주제 · 각 21문장 · 다양한 문형 포함)
const TOPICS = [
  {
    "topic": "Coffee & Café",
    "sentences": [
      "Could I get a medium latte to go?",
      "I usually drink two cups before 10 a.m.",
      "If I had known it was decaf, I wouldn’t have ordered another.",
      "She had already finished her espresso when I arrived.",
      "I’ve never tried their single-origin pour-over.",
      "Can you make it half sweet, please?",
      "There was a long line at the café yesterday.",
      "I will try a new coffee shop tomorrow.",
      "Do you take Apple Pay here?",
      "I had been waiting for ten minutes when they called my name.",
      "Please add an extra shot in that.",
      "What pastry do you recommend this morning?",
      "The cold brew is stronger than I expected.",
      "I wish I could drink coffee at night without losing sleep.",
      "By the time I got there, they had run out of croissants.",
      "I’ve just spilled some coffee on the desk.",
      "Would you mind warming this up a little more?",
      "Mind if I grab a seat by the outlet?",
      "Had I known about this café earlier, I would have come sooner.",
      "I was sipping my cappuccino while reading a book.",
      "Let’s try their seasonal special today."
    ]
  },
  {
    "topic": "Morning Routine",
    "sentences": [
      "Did you brush your teeth after waking up?",
      "I always make my bed before breakfast.",
      "If I had gone to bed earlier, I wouldn’t feel this tired.",
      "She had already left for school when I woke up.",
      "I’ve just finished a short meditation.",
      "What time do you usually wake up on weekends?",
      "I was preparing my lunch while listening to the radio.",
      "Please open the window for fresh air.",
      "He will take a shower after his run.",
      "Had I prepared my clothes last night, I wouldn’t be late.",
      "I often skip breakfast when I’m in a hurry.",
      "Do you check your phone first thing in the morning?",
      "I used to drink only water after waking.",
      "By the time I came downstairs, Dad had already made coffee.",
      "Let’s stretch for ten minutes before we start the day.",
      "I’ve packed my bag, so I’m ready to go.",
      "Was she still sleeping at eight?",
      "I wrote today’s to-do list before leaving home.",
      "If it rains, I’ll take the bus instead of walking.",
      "I was brushing my hair while my sister was eating.",
      "Don’t forget to water the plants before leaving."
    ]
  },
  {
    "topic": "Commuting",
    "sentences": [
      "Do you take the bus or the subway to work?",
      "I usually spend thirty minutes commuting.",
      "If I had left earlier, I wouldn’t have missed the train.",
      "She had already boarded when I reached the platform.",
      "I’ve been stuck in traffic for an hour.",
      "Can I sit here, or is this seat taken?",
      "I was listening to a podcast on the bus.",
      "Please tap your card at the turnstile.",
      "He will carpool with his colleague tomorrow.",
      "Had I known about the delay, I would have left home sooner.",
      "I missed my stop yesterday.",
      "Do you read books on the train?",
      "I often walk to work when the weather is nice.",
      "By the time I arrived, the train had just left.",
      "Let’s grab a quick coffee on the way.",
      "I was cycling while my friend was taking the bus.",
      "How long does your commute take?",
      "I’ll take a taxi if I’m running late.",
      "I had been waiting at the bus stop for fifteen minutes.",
      "Don’t block the door while people are getting off.",
      "I enjoy people-watching during my commute."
    ]
  },
  {
    "topic": "Emails",
    "sentences": [
      "Do you check your email every morning?",
      "I usually reply to important messages first.",
      "If I had attached the file, they wouldn’t have asked again.",
      "She had already sent the report before the deadline.",
      "I’ve just received an invitation in my inbox.",
      "Can you proofread this message for me?",
      "I was writing an email when the phone rang.",
      "Please CC my manager on this thread.",
      "He will send the draft later today.",
      "Had I known his address, I would have emailed him directly.",
      "I deleted five spam emails this morning.",
      "Do you use folders to organize your inbox?",
      "I used to ignore promotional messages.",
      "By the time I opened the email, the meeting had already started.",
      "Let’s write a polite thank-you note.",
      "I’ve checked my inbox; there are no new messages.",
      "Was she sending an email at that moment?",
      "I replied quickly to his question.",
      "If you need details, I’ll forward the original message.",
      "I had been drafting the email for half an hour.",
      "Don’t forget to check attachments before sending."
    ]
  },
  {
    "topic": "Meetings",
    "sentences": [
      "Do you attend many meetings each week?",
      "I usually take notes during discussions.",
      "If I had read the agenda, I would have been better prepared.",
      "She had already presented when I entered the room.",
      "I’ve joined three online meetings today.",
      "Can you share your screen, please?",
      "I was listening carefully when they asked a question.",
      "Please mute your microphone when not speaking.",
      "He will summarize the key points at the end.",
      "Had I been on time, I wouldn’t have missed the opening remarks.",
      "I disagreed politely with one suggestion.",
      "Do you prefer online or face-to-face meetings?",
      "I used to feel nervous about speaking up.",
      "By the time the meeting ended, two hours had passed.",
      "Let’s schedule a follow-up next week.",
      "I’ve already shared the slides with the team.",
      "Were they still discussing the budget then?",
      "I asked a question during Q&A.",
      "If she presents tomorrow, I’ll take notes for her.",
      "I had been preparing my report before the meeting started.",
      "Don’t forget to send the minutes afterward."
    ]
  },
  {
    "topic": "Exercise",
    "sentences": [
      "Do you exercise every day?",
      "I usually go jogging in the park.",
      "If I had joined the gym earlier, I would be fitter now.",
      "She had already finished her workout before breakfast.",
      "I’ve been practicing yoga for three months.",
      "Can you show me how to use this machine?",
      "I was lifting weights when you called.",
      "Please stretch before you start.",
      "He will join the basketball game this evening.",
      "Had I brought my sneakers, I would have exercised too.",
      "I skipped my workout yesterday because of the rain.",
      "Do you enjoy swimming as exercise?",
      "I used to run every morning in high school.",
      "By the time I reached the park, the class had started.",
      "Let’s try a new Pilates routine today.",
      "I’ve already walked ten thousand steps.",
      "Were they still practicing when you left?",
      "I encouraged my friend to work out with me.",
      "If it’s sunny tomorrow, I’ll go hiking.",
      "I had been training for a month before the marathon.",
      "Don’t forget to drink water while exercising."
    ]
  },
  {
    "topic": "Walking",
    "sentences": [
      "Do you take a walk after dinner?",
      "I often walk my dog in the morning.",
      "If I had walked faster, I would have caught the bus.",
      "She had already gone for a walk before lunch.",
      "I’ve just returned from a long walk.",
      "Can you join me for a walk this evening?",
      "I was walking along the river when it started to rain.",
      "Please use the crosswalk for safety.",
      "He will walk to school tomorrow.",
      "Had I known the park was closed, I wouldn’t have gone.",
      "I felt refreshed after my walk yesterday.",
      "Do you like walking in the rain?",
      "I used to take long walks on weekends.",
      "By the time I arrived, they had finished walking.",
      "Let’s walk to the café instead of driving.",
      "I’ve walked more than five kilometers today.",
      "Were you walking home when I called?",
      "I stopped to look at the flowers.",
      "If it doesn’t rain, I’ll walk to work.",
      "I had been walking for an hour before I sat down.",
      "Don’t forget to wear comfortable shoes."
    ]
  },
  {
    "topic": "Grocery Shopping",
    "sentences": [
      "Do you go grocery shopping every week?",
      "I usually write a list before leaving home.",
      "If I had remembered the coupons, I would have saved money.",
      "She had already bought milk before I got to the store.",
      "I’ve just paid for the groceries.",
      "Can you grab some eggs from that shelf?",
      "I was looking for rice when I saw my neighbor.",
      "Please check the expiration date before buying.",
      "He will shop for vegetables tomorrow.",
      "Had I carried a reusable bag, I wouldn’t need plastic ones.",
      "I forgot to buy bread yesterday.",
      "Do you compare prices before you buy?",
      "I used to shop at the local market.",
      "By the time I arrived, they had closed the counter.",
      "Let’s buy some fruit for dessert.",
      "I’ve already picked up everything we need.",
      "Were you still shopping when I called?",
      "I tried a free sample at the store.",
      "If there’s a discount, I’ll buy extra.",
      "I had been waiting in line for ten minutes.",
      "Don’t forget to check the list again."
    ]
  },
  {
    "topic": "Cooking",
    "sentences": [
      "Do you cook dinner every night?",
      "I usually make pasta on weekends.",
      "If I had followed the recipe, it would have tasted better.",
      "She had already cooked rice before I set the table.",
      "I’ve tried baking cookies for the first time.",
      "Can you chop the onions for me?",
      "I was frying eggs when the phone rang.",
      "Please wash the vegetables first.",
      "He will cook steak tonight.",
      "Had I added more salt, the soup would have been tastier.",
      "I prepared lunch boxes yesterday.",
      "Do you enjoy trying new recipes?",
      "I used to help my mom in the kitchen.",
      "By the time we sat down, the food had cooled.",
      "Let’s bake a cake together.",
      "I’ve cooked three dishes already.",
      "Were you still cooking when they arrived?",
      "I boiled the pasta until it was soft.",
      "If you mix these spices, it’ll taste amazing.",
      "I had been cooking all afternoon before guests came.",
      "Don’t forget to turn off the stove."
    ]
  },
  {
    "topic": "Mentor Advice",
    "sentences": [
      "I asked what success looks like before giving advice.",
      "I listened fully before suggesting the next step.",
      "If I had understood earlier, I could have guided better.",
      "She had already prepared her questions before we met.",
      "I’ve often encouraged them to take small steps.",
      "Can you share the main challenge you’re facing?",
      "I was giving feedback when the call was interrupted.",
      "Please highlight strengths before pointing out gaps.",
      "He will follow up with his mentee tomorrow.",
      "Had I known his goals, I would have advised differently.",
      "I celebrated a small win with my mentee yesterday.",
      "Do you want practical tips or reassurance?",
      "I used to give too much advice at once.",
      "By the time we finished, she had drafted a plan.",
      "Let’s set realistic goals together.",
      "I’ve written down the key takeaways.",
      "Were you still reflecting when I called?",
      "I gave feedback privately and praised publicly.",
      "If you try this approach, you’ll see improvements.",
      "I had been mentoring him for a year before he was promoted.",
      "Don’t forget that growth takes time."
    ]
  }
];

export { TOPICS };
