Array.isArray(TOPICS) && TOPICS.length   // → (예: 10, 20, 100 ...)
Array.isArray(TITLES) && TITLES.length   // → TOPICS 개수와 동일해야 정상
typeof bank21                            // → "function"
TOPIC_BANKS[TITLES[0]].length            // → 21 이어야 정상
// Fully handcrafted topics.js — 100 topics × 21 sentences each
(function(){
  window.TITLES = [
    "Morning Routine",
    "Commuting",
    "Coffee Break",
    "Emails",
    "Team Meeting",
    "Project Update",
    "Lunch Out",
    "Groceries",
    "Gym",
    "Evening Walk",
    "Streaming Show",
    "Weekend Plan",
    "Laundry",
    "Room Cleaning",
    "Errands",
    "Bank Visit",
    "Pharmacy",
    "Salon",
    "Car Wash",
    "Pet Care",
    "Cooking Dinner",
    "Takeout",
    "Birthday Party",
    "Small Talk",
    "Weather Chat",
    "Sports Talk",
    "News Catch-up",
    "Book Club",
    "Movie Night",
    "Concert",
    "Coffee Chat",
    "Study Session",
    "Library Visit",
    "Note Taking",
    "Presentation Prep",
    "Public Speaking",
    "Mentor Advice",
    "Goal Setting",
    "Habit Tracking",
    "Budgeting",
    "Online Shopping",
    "Return/Refund",
    "Customer Service",
    "Travel Plan",
    "Packing",
    "Airport",
    "Hotel Check-in",
    "City Tour",
    "Photo Walk",
    "Museum",
    "Park Picnic",
    "Beach Day",
    "Hiking",
    "Rainy Day",
    "Snow Day",
    "Heat Wave",
    "Cold Snap",
    "Sick Day",
    "Clinic Visit",
    "Dentist Visit",
    "Back to Work",
    "Overtime",
    "Deadline Push",
    "Celebration",
    "Thank-you Notes",
    "Apology",
    "Making Plans",
    "Canceling Plans",
    "Running Late",
    "Time Management",
    "Morning Coffee",
    "Afternoon Slump",
    "Power Nap",
    "Evening Class",
    "Night Drive",
    "Late Snack",
    "Phone Call",
    "Video Call",
    "Texting",
    "Social Media",
    "Digital Detox",
    "Mindfulness",
    "Journaling",
    "Reading",
    "Music Playlist",
    "Podcast",
    "Language Practice",
    "Networking",
    "Interview Prep",
    "Part-time Job",
    "Side Project",
    "Coding Session",
    "Design Draft",
    "Feedback Round",
    "Revision",
    "Final Review",
    "Presentation Day",
    "Rest Day",
    "Family Dinner",
    "Friends Hangout",
    "Date Night",
    "Neighborhood Walk",
    "Farmer’s Market",
    "Car Maintenance",
    "House Plants",
    "Recycling",
    "Donation",
    "Volunteering",
    "Community Event",
    "Holiday Prep"
  ];

// topics.js (1~10번 주제 · 각 21문장 · 다양한 문형 포함)
const TOPICS = [
  {
    "topic": "Coffee & Café",
    "sentences": [
      "Could I get a medium latte to go?",
      "I usually drink two cups before 10 a.m.",
      "If I had known it was decaf, I wouldn’t have ordered another.",
      "She had already finished her espresso when I arrived.",
      "I’ve never tried their single-origin pour-over.",
      "Can you make it half sweet, please?",
      "There was a long line at the café yesterday.",
      "I will try a new coffee shop tomorrow.",
      "Do you take Apple Pay here?",
      "I had been waiting for ten minutes when they called my name.",
      "Please add an extra shot in that.",
      "What pastry do you recommend this morning?",
      "The cold brew is stronger than I expected.",
      "I wish I could drink coffee at night without losing sleep.",
      "By the time I got there, they had run out of croissants.",
      "I’ve just spilled some coffee on the desk.",
      "Would you mind warming this up a little more?",
      "Mind if I grab a seat by the outlet?",
      "Had I known about this café earlier, I would have come sooner.",
      "I was sipping my cappuccino while reading a book.",
      "Let’s try their seasonal special today."
    ]
  },
  {
    "topic": "Morning Routine",
    "sentences": [
      "Did you brush your teeth after waking up?",
      "I always make my bed before breakfast.",
      "If I had gone to bed earlier, I wouldn’t feel this tired.",
      "She had already left for school when I woke up.",
      "I’ve just finished a short meditation.",
      "What time do you usually wake up on weekends?",
      "I was preparing my lunch while listening to the radio.",
      "Please open the window for fresh air.",
      "He will take a shower after his run.",
      "Had I prepared my clothes last night, I wouldn’t be late.",
      "I often skip breakfast when I’m in a hurry.",
      "Do you check your phone first thing in the morning?",
      "I used to drink only water after waking.",
      "By the time I came downstairs, Dad had already made coffee.",
      "Let’s stretch for ten minutes before we start the day.",
      "I’ve packed my bag, so I’m ready to go.",
      "Was she still sleeping at eight?",
      "I wrote today’s to-do list before leaving home.",
      "If it rains, I’ll take the bus instead of walking.",
      "I was brushing my hair while my sister was eating.",
      "Don’t forget to water the plants before leaving."
    ]
  },
  {
    "topic": "Commuting",
    "sentences": [
      "Do you take the bus or the subway to work?",
      "I usually spend thirty minutes commuting.",
      "If I had left earlier, I wouldn’t have missed the train.",
      "She had already boarded when I reached the platform.",
      "I’ve been stuck in traffic for an hour.",
      "Can I sit here, or is this seat taken?",
      "I was listening to a podcast on the bus.",
      "Please tap your card at the turnstile.",
      "He will carpool with his colleague tomorrow.",
      "Had I known about the delay, I would have left home sooner.",
      "I missed my stop yesterday.",
      "Do you read books on the train?",
      "I often walk to work when the weather is nice.",
      "By the time I arrived, the trai
